### PR TITLE
Add dev and native exclusions, exclude camel-quarkus-fhir in native

### PR DESCRIPTION
**Pull request by jsmrcka**
`camel-quarkus-fhir` exceeds the `-Dquarkus.native.native-image-xmx=4g` limit.

### CODE REVIEW

**Comment by rsvoboda** [comment]
This will skip native build if the app contains camel-quarkus-fhir, correct?

**Comment by jsmrcka** [comment]
> This will skip native build if the app contains camel-quarkus-fhir, correct?

Yes. The same goes for dev mode exclusions (currently unused, but might come in handy).

**Comment by rsvoboda** [comment]
@jsmrcka can you pls look into the fail?
It's camel-quarkus-microprofile-health-camel-quarkus-sql-smallrye-reactive-messaging-spring-data-jpa.log
It's probably something with camel extensions :/

**Comment by rsvoboda** [comment]
CC @vkasala / @llowinge

**Comment by jsmrcka** [comment]
> @jsmrcka can you pls look into the fail? It's camel-quarkus-microprofile-health-camel-quarkus-sql-smallrye-reactive-messaging-spring-data-jpa.log It's probably something with camel extensions :/

Combination of `quarkus-spring-data-jpa` and `camel-quarkus-sql` fails with
```
com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: org.springframework.util.ObjectUtils.nullSafeConciseToString(java.lang.Object)
```
(or similar) during native build.

There are different versions of `org.springframework.util.ObjectUtils` coming from:
```
[INFO] +- io.quarkus:quarkus-spring-data-jpa:jar:3.5.0:compile
[INFO] |  \- io.quarkus:quarkus-spring-core-api:jar:5.2.SP7:compile
[INFO] \- org.apache.camel.quarkus:camel-quarkus-sql:jar:3.5.0:compile
[INFO]    \- org.apache.camel.quarkus:camel-quarkus-support-spring:jar:3.5.0:compile
[INFO]       \- org.apache.camel.quarkus:camel-quarkus-support-spring-core:jar:3.5.0:compile
```

**Review by rsvoboda — APPROVED** [review]

**Comment by jamesnetherton** [comment]
> camel-quarkus-fhir exceeds the -Dquarkus.native.native-image-xmx=4g

The native build for FHIR is unfortunately quite demanding on memory. A *lot* of stuff ends up being registered for reflection. It's a known issue that we could try to improve in future:

https://github.com/apache/camel-quarkus/issues/654

> Combination of `quarkus-spring-data-jpa` and `camel-quarkus-sql`

Combining `quarkus-spring-*` with Camel components that use Spring (like the SQL component) is not something we really support. Quarkus / Camel likely use different Spring versions and we're pretty unlikely ever be in perfect alignment, given that the Spring version in Camel is driven by the version of Spring Boot a given release supports.

**Pull request merged**
