### PR TITLE
Update Quarkus version to 3.9.3

### PR DESCRIPTION
**Pull request by jedla97**
Update to the latest version

### CODE REVIEW

**Comment by rsvoboda** [comment]
@jedla97 many failures in ci :/

**Comment by jedla97** [comment]
Forget to add the renamed artifact + non-reactive rest artifacts wasn't renamed from 3.7. Waiting for CI but now it should be all.

**Comment by jedla97** [comment]
There seems to be a problem with resteasy-qute on windows when building the native. Looking into this

**Comment by jedla97** [comment]
CI is green so it should be fine merge. I also run few run on my fork and all were green.

**Review by rsvoboda — APPROVED** [review]

**Pull request merged**
